// M14 C1: fantasy labels (docs/design/battles.md 3.7). Generated-style table; edit by hand.
import type { BattleLabels } from '../labels';

export const GUILD_LABELS: BattleLabels = {
  move: {
    "commit": "Slash",
    "assert": "Parry",
    "sketch": "Rune Sketch",
    "audit": "Appraise",
    "comment": "Scribe's Note",
    "query": "Scry",
    "delegate": "Command",
    "shove": "Shove",
    "hotfix": "Mending Rune",
    "refactor-strike": "Cleaving Arc",
    "stack-trace": "Binding Glyph",
    "rubber-duck": "Calm Spirit",
    "quick-deploy": "Swift Strike",
    "ship-it": "Final Forge",
    "flaky-repro": "Trial by Fire",
    "regression-suite": "Gauntlet Run",
    "unit-test-shield": "Ward of Proof",
    "green-build": "Healing Draught",
    "smoke-test": "Probing Jab",
    "fuzz-barrage": "Thousand Needles",
    "blueprint-beam": "Moonlit Ray",
    "grand-design": "Grand Ritual",
    "load-bearing-wall": "Bastion Wall",
    "decouple": "Unravel",
    "whiteboard-trap": "Rune Snare",
    "paradigm-shift": "Shifting Sigil",
    "pen-test": "Lockpick",
    "zero-day": "Shadow Strike",
    "firewall": "Aegis",
    "incident-response": "Sanctuary",
    "threat-model": "Foresight",
    "lockdown": "Seal of Silence",
    "nitpick": "Pinprick",
    "blocking-review": "Judge's Verdict",
    "lgtm": "Blessing",
    "style-guide": "Codex Ward",
    "drive-by-comment": "Passing Remark",
    "merge-conflict": "Tangling Hex",
    "grep-scan": "Rune Reading",
    "root-cause": "Truth Seeker",
    "risk-register": "Ledger Ward",
    "data-driven": "Sage's Wisdom",
    "spreadsheet-storm": "Tome Storm",
    "deep-dive": "Deep Delve",
    "escalate": "Rally",
    "crunch-time": "Berserk Rush",
    "roadmap": "Battle Plan",
    "team-lunch": "Feast Hall",
    "standup": "Rouse the Guild",
    "pep-talk": "Battle Hymn",
    "power-swing": "Power Swing",
    "heroic-charge": "Heroic Charge",
    "brace": "Brace",
    "second-wind": "Second Wind",
    "trip": "Trip",
    "last-stand": "Last Stand",
    "segfault": "Gnash",
    "null-pointer": "Venom Bite",
    "race-condition": "Curse of Tangles",
    "memory-leak": "Sapping Curse",
    "citation": "Decree",
    "paperwork-pile": "Scroll Slam",
    "red-tape": "Sealing Wax",
    "by-the-book": "Letter of the Law",
    "redact": "Black Ink",
    "classified": "Sealed Orders",
    "surveillance": "Spyglass",
    "interrogate": "Cross-Examine",
    "pitch": "Barter",
    "upsell": "Haggle",
    "cold-call": "Dazzling Patter",
    "synergy": "Gold Aura",
    "small-talk": "Idle Chatter",
    "hot-take": "Wild Boast",
    "humblebrag": "Preen",
    "name-drop": "Name Drop",
    "scratch": "Claw",
    "zoomies": "Mad Dash",
    "keyboard-walk": "Paw Stomp",
    "hairball": "Fur Ball",
  },
  item: {
    "coffee": "Healing Tonic",
    "energy-drink": "Elixir of Focus",
    "rubber-duck": "Cleansing Charm",
    "pizza": "Feast Platter",
  },
  class: {
    "developer": "Artificer",
    "qa": "Warden",
    "architect": "Loremaster",
    "security": "Shadow Knight",
    "reviewer": "Arbiter",
    "analyst": "Sage",
    "lead": "Guild Master",
    "adventurer": "Adventurer",
  },
  loot: {
    "hat-cap": "Guild Cap",
    "hat-police-cap": "Watch Helm",
    "hat-fedora": "Hooded Cap",
    "hat-hardhat": "Iron Helm",
    "prop-mop": "Scrub Broom",
    "prop-parcel": "Sealed Parcel",
    "prop-watering-can": "Dew Can",
    "prop-clipboard": "Quest Scroll",
    "title-bug-squasher": "Slime Slayer",
    "title-red-tape-cutter": "Tape Cutter",
    "title-redacted": "Blackened",
    "title-unsold": "Unbought",
    "title-rival-tamer": "Rival Tamer",
    "title-cat-whisperer": "Cat Whisperer",
  },
  enemy: {
    "guest": "Wanderer",
    "police": "Town Watch",
    "cia-agent": "Royal Spy",
    "sales-dog": "Merchant Hound",
    "monster": "Dungeon Slime",
    "office-cat": "Guild Cat",
  },
  type: {
    "build": "Forge",
    "test": "Proof",
    "design": "Arcane",
    "secure": "Shadow",
    "review": "Judgment",
    "insight": "Lore",
    "lead": "Command",
    "grit": "Valor",
    "bug": "Vermin",
    "bureaucrat": "Decree",
    "salesy": "Barter",
    "rival": "Duel",
    "feral": "Wild",
    "neutral": "Neutral",
  },
  status: {
    "stunned": "Stunned",
    "merge-conflict": "Tangled",
    "burnout": "Weary",
    "buffed": "Inspired",
    "shielded": "Warded",
  },
  branch: {
    "developer.0": "Forge-Fire",
    "developer.1": "Fine Craft",
    "developer.2": "Quick Hands",
    "qa.0": "Trial",
    "qa.1": "Bulwark",
    "qa.2": "Keen Eyes",
    "architect.0": "Grand Design",
    "architect.1": "Stone Wards",
    "architect.2": "Star Charts",
    "security.0": "Blade",
    "security.1": "Shadowcraft",
    "security.2": "Vigilance",
    "reviewer.0": "Judgment",
    "reviewer.1": "Sanctity",
    "reviewer.2": "Quick Wit",
    "analyst.0": "Scholarship",
    "analyst.1": "Foresight",
    "analyst.2": "Swift Study",
    "lead.0": "Command",
    "lead.1": "Hearth",
    "lead.2": "Rally",
    "adventurer.0": "Might",
    "adventurer.1": "Hardiness",
    "adventurer.2": "Cunning",
  },
  skill: {},
};
