// M14 C1: office satire labels (docs/design/battles.md 3.7). Generated-style table; edit by hand.
import type { BattleLabels } from '../labels';

export const MODERN_LABELS: BattleLabels = {
  move: {
    "commit": "Commit",
    "assert": "Assert",
    "sketch": "Whiteboard Sketch",
    "audit": "Audit",
    "comment": "Review Comment",
    "query": "SQL Query",
    "delegate": "Delegate",
    "shove": "Shove",
    "hotfix": "Hotfix",
    "refactor-strike": "Refactor Strike",
    "stack-trace": "Stack Trace",
    "rubber-duck": "Rubber Duck",
    "quick-deploy": "Quick Deploy",
    "ship-it": "Ship It",
    "flaky-repro": "Flaky Repro",
    "regression-suite": "Regression Suite",
    "unit-test-shield": "Unit-Test Shield",
    "green-build": "Green Build",
    "smoke-test": "Smoke Test",
    "fuzz-barrage": "Fuzz Barrage",
    "blueprint-beam": "Blueprint Beam",
    "grand-design": "Grand Design",
    "load-bearing-wall": "Load-Bearing Wall",
    "decouple": "Decouple",
    "whiteboard-trap": "Whiteboard Trap",
    "paradigm-shift": "Paradigm Shift",
    "pen-test": "Pen Test",
    "zero-day": "Zero-Day",
    "firewall": "Firewall",
    "incident-response": "Incident Response",
    "threat-model": "Threat Model",
    "lockdown": "Lockdown",
    "nitpick": "Nitpick",
    "blocking-review": "Blocking Review",
    "lgtm": "LGTM",
    "style-guide": "Style Guide",
    "drive-by-comment": "Drive-By Comment",
    "merge-conflict": "Merge Conflict",
    "grep-scan": "Grep Scan",
    "root-cause": "Root Cause",
    "risk-register": "Risk Register",
    "data-driven": "Data-Driven",
    "spreadsheet-storm": "Spreadsheet Storm",
    "deep-dive": "Deep Dive",
    "escalate": "Escalate",
    "crunch-time": "Crunch Time",
    "roadmap": "Roadmap",
    "team-lunch": "Team Lunch",
    "standup": "Standup",
    "pep-talk": "Pep Talk",
    "power-swing": "Power Swing",
    "heroic-charge": "Heroic Charge",
    "brace": "Brace",
    "second-wind": "Second Wind",
    "trip": "Trip",
    "last-stand": "Last Stand",
    "segfault": "Segfault",
    "null-pointer": "Null Pointer",
    "race-condition": "Race Condition",
    "memory-leak": "Memory Leak",
    "citation": "Citation",
    "paperwork-pile": "Paperwork Pile",
    "red-tape": "Red Tape",
    "by-the-book": "By the Book",
    "redact": "Redact",
    "classified": "Classified",
    "surveillance": "Surveillance",
    "interrogate": "Interrogate",
    "pitch": "Pitch",
    "upsell": "Upsell",
    "cold-call": "Cold Call",
    "synergy": "Synergy",
    "small-talk": "Small Talk",
    "hot-take": "Hot Take",
    "humblebrag": "Humblebrag",
    "name-drop": "Name Drop",
    "scratch": "Scratch",
    "zoomies": "Zoomies",
    "keyboard-walk": "Keyboard Walk",
    "hairball": "Hairball",
  },
  item: {
    "coffee": "Coffee",
    "energy-drink": "Energy Drink",
    "rubber-duck": "Rubber Duck",
    "pizza": "Team Pizza",
  },
  class: {
    "developer": "Developer",
    "qa": "QA Engineer",
    "architect": "Architect",
    "security": "Security Engineer",
    "reviewer": "Code Reviewer",
    "analyst": "Analyst",
    "lead": "Tech Lead",
    "adventurer": "Intern",
  },
  loot: {
    "hat-cap": "Company Cap",
    "hat-police-cap": "Police Cap",
    "hat-fedora": "Fedora",
    "hat-hardhat": "Hard Hat",
    "prop-mop": "Office Mop",
    "prop-parcel": "Parcel",
    "prop-watering-can": "Watering Can",
    "prop-clipboard": "Clipboard",
    "title-bug-squasher": "Bug Squasher",
    "title-red-tape-cutter": "Red Tape Cutter",
    "title-redacted": "Redacted",
    "title-unsold": "Unsold",
    "title-rival-tamer": "Rival Tamer",
    "title-cat-whisperer": "Cat Whisperer",
  },
  enemy: {
    "guest": "Guest",
    "police": "Compliance Cop",
    "cia-agent": "Agent Smith",
    "sales-dog": "Sales Dog",
    "monster": "Production Bug",
    "office-cat": "Office Cat",
  },
  type: {
    "build": "Build",
    "test": "Test",
    "design": "Design",
    "secure": "Secure",
    "review": "Review",
    "insight": "Insight",
    "lead": "Lead",
    "grit": "Grit",
    "bug": "Bug",
    "bureaucrat": "Red Tape",
    "salesy": "Hustle",
    "rival": "Rivalry",
    "feral": "Feral",
    "neutral": "Plain",
  },
  status: {
    "stunned": "Stunned",
    "merge-conflict": "Merge Conflict",
    "burnout": "Burnout",
    "buffed": "Fired Up",
    "shielded": "Shielded",
  },
  branch: {
    "developer.0": "Feature Work",
    "developer.1": "Clean Code",
    "developer.2": "Hot Deploys",
    "qa.0": "Coverage",
    "qa.1": "Safety Net",
    "qa.2": "Fast Feedback",
    "architect.0": "Big Picture",
    "architect.1": "Solid Foundations",
    "architect.2": "Whiteboard Wizardry",
    "security.0": "Offense",
    "security.1": "Hardening",
    "security.2": "Response",
    "reviewer.0": "Strict Reviews",
    "reviewer.1": "Approvals",
    "reviewer.2": "Quick Takes",
    "analyst.0": "Digging In",
    "analyst.1": "Dashboards",
    "analyst.2": "Quick Queries",
    "lead.0": "Management",
    "lead.1": "Team Care",
    "lead.2": "Meetings",
    "adventurer.0": "Hustle",
    "adventurer.1": "Grit",
    "adventurer.2": "Improvisation",
  },
  skill: {},
};
