// M14 C1: sci-fi labels (docs/design/battles.md 3.7). Generated-style table; edit by hand.
import type { BattleLabels } from '../labels';

export const RIFT_LABELS: BattleLabels = {
  move: {
    "commit": "Commit Pulse",
    "assert": "Assert Beam",
    "sketch": "Hologram Sketch",
    "audit": "Scan",
    "comment": "Ping",
    "query": "Query Probe",
    "delegate": "Delegate Drone",
    "shove": "Shove",
    "hotfix": "Patch Pulse",
    "refactor-strike": "Refactor Beam",
    "stack-trace": "Trace Bolt",
    "rubber-duck": "Repair Drone",
    "quick-deploy": "Warp Deploy",
    "ship-it": "Final Build",
    "flaky-repro": "Chaos Probe",
    "regression-suite": "Regression Sweep",
    "unit-test-shield": "Test Barrier",
    "green-build": "Reboot",
    "smoke-test": "Smoke Pulse",
    "fuzz-barrage": "Fuzz Storm",
    "blueprint-beam": "Blueprint Lance",
    "grand-design": "Grand Schematic",
    "load-bearing-wall": "Bulkhead",
    "decouple": "Decouple",
    "whiteboard-trap": "Gravity Trap",
    "paradigm-shift": "Phase Shift",
    "pen-test": "Breach Test",
    "zero-day": "Zero-Day",
    "firewall": "Shield Grid",
    "incident-response": "Emergency Protocol",
    "threat-model": "Threat Matrix",
    "lockdown": "Lockdown",
    "nitpick": "Needle Ping",
    "blocking-review": "Veto Ray",
    "lgtm": "Green Light",
    "style-guide": "Protocol Shell",
    "drive-by-comment": "Fly-By Comm",
    "merge-conflict": "Desync",
    "grep-scan": "Grid Scan",
    "root-cause": "Core Trace",
    "risk-register": "Hazard Index",
    "data-driven": "Data Surge",
    "spreadsheet-storm": "Signal Storm",
    "deep-dive": "Deep Scan",
    "escalate": "Escalate",
    "crunch-time": "Overclock",
    "roadmap": "Star Chart",
    "team-lunch": "Mess Hall",
    "standup": "Fleet Comm",
    "pep-talk": "Rally Signal",
    "power-swing": "Power Swing",
    "heroic-charge": "Heroic Charge",
    "brace": "Brace",
    "second-wind": "Second Wind",
    "trip": "Trip",
    "last-stand": "Last Stand",
    "segfault": "Segfault",
    "null-pointer": "Null Beam",
    "race-condition": "Desync Spore",
    "memory-leak": "Core Leak",
    "citation": "Citation Ray",
    "paperwork-pile": "Form Storm",
    "red-tape": "Stasis Tape",
    "by-the-book": "By the Protocol",
    "redact": "Redact",
    "classified": "Classified",
    "surveillance": "Sensor Sweep",
    "interrogate": "Interrogate",
    "pitch": "Pitch Bolt",
    "upsell": "Upsell Burst",
    "cold-call": "Cold Hail",
    "synergy": "Synergy Core",
    "small-talk": "Small Talk",
    "hot-take": "Hot Take",
    "humblebrag": "Hype Field",
    "name-drop": "Name Drop",
    "scratch": "Claw Swipe",
    "zoomies": "Warp Dash",
    "keyboard-walk": "Keystroke Storm",
    "hairball": "Hairball Mine",
  },
  item: {
    "coffee": "Caffeine Cell",
    "energy-drink": "Energy Cell",
    "rubber-duck": "Nano Duck",
    "pizza": "Ration Pack",
  },
  class: {
    "developer": "Engineer",
    "qa": "Tester Unit",
    "architect": "Architect AI",
    "security": "Security Officer",
    "reviewer": "Auditor",
    "analyst": "Analyst Unit",
    "lead": "Commander",
    "adventurer": "Cadet",
  },
  loot: {
    "hat-cap": "Fleet Cap",
    "hat-police-cap": "Patrol Cap",
    "hat-fedora": "Stealth Hat",
    "hat-hardhat": "Helmet",
    "prop-mop": "Cleaner Drone",
    "prop-parcel": "Cargo Pod",
    "prop-watering-can": "Hydro Can",
    "prop-clipboard": "Data Slate",
    "title-bug-squasher": "Void Purger",
    "title-red-tape-cutter": "Red Tape Cutter",
    "title-redacted": "Redacted",
    "title-unsold": "Unsold",
    "title-rival-tamer": "Rival Tamer",
    "title-cat-whisperer": "Cat Whisperer",
  },
  enemy: {
    "guest": "Visitor",
    "police": "Patrol Droid",
    "cia-agent": "Agent Zero",
    "sales-dog": "Sales Hound",
    "monster": "Glitch Entity",
    "office-cat": "Station Cat",
  },
  type: {
    "build": "Build",
    "test": "Test",
    "design": "Design",
    "secure": "Secure",
    "review": "Review",
    "insight": "Insight",
    "lead": "Command",
    "grit": "Grit",
    "bug": "Glitch",
    "bureaucrat": "Protocol",
    "salesy": "Pitch",
    "rival": "Rival",
    "feral": "Feral",
    "neutral": "Neutral",
  },
  status: {
    "stunned": "Stunned",
    "merge-conflict": "Desynced",
    "burnout": "Overheated",
    "buffed": "Boosted",
    "shielded": "Shielded",
  },
  branch: {
    "developer.0": "Weapons",
    "developer.1": "Systems",
    "developer.2": "Thrusters",
    "qa.0": "Diagnostics",
    "qa.1": "Shields",
    "qa.2": "Rapid Scan",
    "architect.0": "Schematics",
    "architect.1": "Hull",
    "architect.2": "Navigation",
    "security.0": "Offense",
    "security.1": "Hardening",
    "security.2": "Response",
    "reviewer.0": "Audit",
    "reviewer.1": "Clearance",
    "reviewer.2": "Quick Comms",
    "analyst.0": "Deep Scan",
    "analyst.1": "Telemetry",
    "analyst.2": "Fast Query",
    "lead.0": "Command",
    "lead.1": "Crew Care",
    "lead.2": "Briefings",
    "adventurer.0": "Combat",
    "adventurer.1": "Armor",
    "adventurer.2": "Improv",
  },
  skill: {},
};
