fn main() {
    // Our own commands get explicit permissions (permissions/autogenerated), so a window can only
    // call them if a capability lists them: see capabilities/main.json.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            "rpc",
            "sidecar_status",
            "sidecar_retry",
            "open_office",
            "find_free_port",
            "reveal_path",
            "updates_configured",
            "check_update",
            "install_update",
        ])),
    )
    .expect("failed to run tauri-build");
}
