import type { NpcContent } from '../types';

/** Rift (sci-fi) NPC skins: same semantic kinds as every style (D2), themed names, looks and lines. Every line <= 48 chars. */
export const RIFT_NPCS: NpcContent = {
  skins: {
    janitor: {
      name: 'Maintenance Drone',
      title: 'Hull Care',
      color: 0xf0c04f,
      costume: { robe: 0x4a5a6a, hat: 'hardhat', hatColor: 0xf0c04f, staff: 'mop' },
      lines: ['Sweeping stardust. Always stardust.', 'Beep. Floor integrity: moderate.', 'Please mind the wet deck.'],
      sound: 'mop',
      jingle: 0,
    },
    courier: {
      name: 'Cargo Runner',
      title: 'Freight',
      color: 0x4ff0d0,
      costume: { robe: 0x2a5a6a, hat: 'cap', hatColor: 0x4ff0d0, staff: 'parcel' },
      lines: ['Package for the command ring!', 'Cargo delivered, sign here.', 'Sealed crate. Do not shake.'],
      jingle: 1,
    },
    'plant-waterer': {
      name: 'Hydroponist',
      title: 'Grow Bay',
      color: 0x6fe08a,
      costume: { robe: 0x2a6a4a, staff: 'watering-can' },
      lines: ['Misting the void-moss.', 'Nutrient drip at ninety percent.', 'Grow, little spores.'],
      jingle: 2,
    },
    guest: {
      name: 'Star Pilgrim',
      title: 'Visitor',
      color: 0xb48cff,
      costume: { robe: 0x5a3a8a, cloak: 0x2a1a5a, hat: 'hood', hatColor: 0x7a5ad0 },
      lines: ['I came through the rift to see this.', 'What a lovely, drifting office.', 'Do you sell directions to Andromeda?'],
      jingle: 3,
    },
    police: {
      name: 'Rift Warden',
      title: 'Patrol',
      color: 0x5aa0ff,
      costume: { robe: 0x2a3a7a, hat: 'police-cap', hatColor: 0x1a2a5a, staff: 'clipboard' },
      lines: ['Rift permits, please.', 'Nobody leaves the sector!', 'Move along, nothing to see here.'],
      sound: 'whistle',
      jingle: 0,
    },
    'cia-agent': {
      name: 'Void Auditor',
      title: 'Classified',
      color: 0x8e8e9e,
      costume: { robe: 0x1a1a2a, hat: 'fedora', hatColor: 0x1a1a2a, shades: true },
      lines: ['This conversation never occurred.', 'The void sees everything.', 'I am only auditing the dark matter.'],
      jingle: 1,
    },
    'sales-dog': {
      name: 'Hover Hound',
      title: 'Sales',
      color: 0x4ff0d0,
      creature: 'hover-hound',
      lines: ['Woof! Buy a warp coil?', 'Arf! Limited offer, one jump only.', 'Bark bark (that means thrusters).'],
      sound: 'bark',
      jingle: 2,
    },
    monster: {
      name: 'Void Blob',
      title: 'Anomaly',
      color: 0xd94ff0,
      creature: 'void-blob',
      lines: ['Bloorp!', 'Gloop gloop gloop.', 'I am a friendly singularity.'],
      sound: 'roar',
      jingle: 3,
    },
    'office-cat': {
      name: 'Astro Cat',
      title: 'Mascot',
      color: 0xf0e0ff,
      creature: 'astro-cat',
      lines: ['Mrrp. The sofa is mine now.', 'Purring at orbital frequency.', 'Mew. Feed me stardust.'],
      sound: 'meow',
      jingle: 1,
    },
  },
};
