import type { LifeContent } from '../types';

/** Rift (sci-fi) idle activities and meeting lines. Same kinds and cast sizes as the other styles (D2); every line <= 48 chars. */
export const RIFT_LIFE: LifeContent = {
  activities: [
    {
      id: 'nutrient-bar',
      requires: ['coffee-machine', 'counter'],
      cast: [2, 3],
      weight: 3,
      durationSec: [14, 24],
      pose: 'sip',
      emote: 'mug',
      lines: ['Nutrient paste, flavour: nebula.', 'Is this one still warm?', 'Synth-caf hits different off-world.', 'Refill the ration cell for me?', 'Mine tastes faintly of ozone.'],
    },
    {
      id: 'coolant-gossip',
      requires: ['water-cooler'],
      cast: [2, 3],
      weight: 3,
      durationSec: [12, 22],
      pose: 'chat',
      emote: 'laugh',
      lines: ['Heard the Nexus drifted two meters.', 'The new pilot hums to the reactor.', 'Who left a rift open in bay three?', 'Rumour: the stairs go somewhere else now.', 'Top secret. Please keep it quiet.'],
    },
    {
      id: 'holo-arcade',
      requires: ['arcade'],
      cast: [1, 2],
      weight: 2,
      durationSec: [14, 26],
      pose: 'play',
      emote: 'gamepad',
      lines: ['New high score on Asteroid Run!', 'The final boss is a sentient moon.', 'One more credit, then back to work.', 'My hands are glowing. That is normal.', 'Press start to leave the atmosphere.'],
    },
    {
      id: 'zero-g-paddle',
      requires: ['ping-pong'],
      cast: [2, 2],
      weight: 2,
      durationSec: [14, 24],
      pose: 'play',
      emote: 'paddle',
      lines: ['The ball hovers. Plan your angle.', 'Gravity off. Spin on.', 'Point! It bounced off the ceiling.', 'No fair, you are using a tractor beam.', 'Rematch at half gravity.'],
    },
    {
      id: 'hover-puck',
      requires: ['foosball'],
      cast: [2, 4],
      weight: 2,
      durationSec: [14, 24],
      pose: 'play',
      emote: 'dice',
      lines: ['Puck is airborne! Defend the goal!', 'Magnet field stable. Go go go!', 'That shot bent spacetime.', 'Tie game, third dimension.', 'Goal! The puck is in orbit.'],
    },
    {
      id: 'holo-chess',
      requires: ['board-game-table'],
      cast: [2, 4],
      weight: 2,
      durationSec: [18, 30],
      pose: 'play',
      emote: 'chess',
      lines: ['Your hologram knight looks nervous.', 'Check, in three dimensions.', 'I move the queen to deck seven.', 'Calculating... you are still losing.', 'The pieces are arguing again.'],
    },
    {
      id: 'gravity-stretch',
      requires: [],
      cast: [1, 1],
      weight: 2,
      durationSec: [8, 14],
      pose: 'stretch',
      lines: ['Recalibrating my spine.', 'Nine hours in a cockpit chair...', 'Gravity feels heavy today.', 'Joints report: nominal. Mostly.'],
    },
    {
      id: 'comm-call',
      requires: [],
      cast: [1, 1],
      weight: 2,
      durationSec: [8, 16],
      pose: 'phone',
      emote: 'phone',
      lines: ['Comm relay is lagging again.', 'Yes, I am still in this sector.', 'Send my regards to Mission Control.', 'Can you repeat that? Static storm.'],
    },
    {
      id: 'void-moss',
      requires: ['plant'],
      cast: [1, 1],
      weight: 2,
      durationSec: [8, 14],
      pose: 'water',
      emote: 'can',
      lines: ['The void-moss glows when it is happy.', 'Trim the tendrils, mist the spores.', 'You are doing great, little organism.', 'It purred. I think it purred.'],
    },
    {
      id: 'stasis-nap',
      requires: ['sofa'],
      cast: [1, 1],
      weight: 1,
      durationSec: [16, 28],
      pose: 'nap',
      emote: 'zz',
      lines: ['Entering stasis for five minutes.', 'Wake me at the next jump.', 'Pod seal engaged. Zzz.', 'Dreaming of a planet with a sky.'],
    },
    {
      id: 'star-chart-doodle',
      requires: ['board'],
      cast: [1, 1],
      weight: 1,
      durationSec: [10, 18],
      pose: 'doodle',
      emote: 'pencil',
      lines: ['Mapping a constellation of my own.', 'This star is named after the intern.', 'Plotting a route home.', 'Is that a nebula or a coffee stain?'],
    },
  ],
  kickoff: {
    invite: ['All crew to the briefing table!', 'Kickoff in the command ring!', 'Mission briefing, everyone. Now!', 'New task incoming. Gather up!'],
    fetch: ['Hey! The briefing started already.', 'Your presence is requested, crew member.', 'We are waiting on you for launch.'],
    dawdle: ['Docking my comm, one second!', 'Just finishing a diagnostic.', 'Coming! My boots were still magnetised.'],
    talk: ['The vector looks clean.', 'Mind the dependencies.', 'I will take the first sector.', 'Sync our ship clocks, please.', 'We jump on my signal.'],
    close: ['Briefing over. Good luck out there.', 'Engage! See you on the other side.', 'Dismissed. Stay in contact.'],
  },
  standup: {
    invite: ['Daily sync at the command ring!', 'Stand-up in thirty seconds.', 'Crew sync. Keep it brief!'],
    fetch: ['Sync is starting without you.', 'Hurry up, we are mid-orbit.', 'Over here, crew member!'],
    dawdle: ['Be right there, finishing a scan.', 'Rerouting my coffee. Almost!', 'Two more seconds, then docked.'],
    talk: ['Yesterday I patched the airlock.', 'Today I chase a stray signal.', 'No blockers. Systems green.', 'Blocked on a missing coordinate.', 'Reactor is stable, thank you.'],
    close: ['Nice sync. Back to your stations.', 'That is all. Safe travels.', 'Adjourned. Ad astra!'],
  },
};
