// M12 G1 drama: pure rules (docs/design/game-office.md sections 1.4 and 2.4). W2-0 ships the final
// constants and signatures; task T1 replaces the stub bodies below.
import type { Agent, Settings } from '@tagconn/shared';
import type { FurnitureKind } from './procgen/types';
import type { DramaAntic, DramaContent, DramaEmote, StrainKind, ThemeDefinition } from './themes/types';

export type DramaSettings = Settings['office']['drama'];

/** Texture keys (generated by textures.ts in T2). The HUD (T3) paints the same bitmaps. */
export const STRAIN_ICON: Record<StrainKind, string> = { dizzy: 'icon-dizzy-1', sweating: 'icon-sweat', tired: 'icon-yawn', 'on-a-roll': 'icon-fire' };
export const DIZZY_FRAMES = ['icon-dizzy-1', 'icon-dizzy-2', 'icon-dizzy-3'] as const;
export const EMOTE_ICON: Record<DramaEmote, string> = {
  mug: 'icon-mug', note: 'icon-note', dice: 'icon-dice', ball: 'icon-ball', phone: 'icon-phone', laugh: 'icon-laugh', spark: 'icon-sparkle', zz: 'icon-zz',
};
export const EMPTY_DRAMA: DramaContent = { antics: [], strain: { dizzy: [], sweating: [], tired: [], 'on-a-roll': [] } };

/** FNV-1a 32-bit (same as Character.ts:45 and seats.ts:6). */
export function dramaHash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}

/** A deterministic [0,1) stream seeded by a string (mulberry32 over dramaHash). */
export function dramaRng(seed: string): () => number {
  let a = dramaHash(seed);
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** floor(nowMs / (idleChatSec * 1000)): the seeding bucket. */
export function dramaBucket(nowMs: number, idleChatSec: number): number {
  return Math.floor(nowMs / (idleChatSec * 1000));
}

/** Delay until the next drama attempt on a floor: idleChatSec * 1000 * (0.5 .. 1.5), seeded by (floorKey, bucket). */
export function nextDramaDelayMs(_floorKey: string, _bucket: number, idleChatSec: number): number {
  return idleChatSec * 1000; // stub (T1)
}

export interface DramaCandidate { key: string; roomId: string; x: number; y: number }
export interface DramaCast { roomId: string; keys: readonly [string] | readonly [string, string] }
/**
 * Who acts next. Ignores rooms in `busyRoomIds`. Seeded pick of a room with candidates; in it, a pair
 * (the two closest by Manhattan distance, ties by key) when 2+ candidates and the seeded coin says "pair"
 * (p = 0.7), else a solo. Deterministic for the same inputs regardless of candidate order.
 */
export function pickCast(_candidates: readonly DramaCandidate[], _busyRoomIds: ReadonlySet<string>, _seed: string): DramaCast | null {
  return null; // stub (T1)
}

/** A seeded antic with `cast === castSize` whose `props` is empty or intersects `roomProps`. */
export function pickAntic(_content: DramaContent, _roomProps: ReadonlySet<FurnitureKind>, _castSize: 1 | 2, _seed: string): DramaAntic | null {
  return null; // stub (T1)
}

/** A seeded exchange of `antic.lines`. */
export function pickExchange(antic: DramaAntic, _seed: string): readonly [string] | readonly [string, string] {
  return antic.lines[0] ?? ['']; // stub (T1)
}

export type StrainInput = Pick<Agent, 'status' | 'activity' | 'startedAt' | 'updatedAt' | 'toolStartedAt'>;
/** Rules in section 2.4. `null` when calm, done, or `cfg.enabled` is false. */
export function strainFor(_agent: StrainInput, _nowMs: number, _cfg: DramaSettings, _onARoll: boolean): StrainKind | null {
  return null; // stub (T1)
}

/** A seeded strain line, or null when the list is empty. */
export function strainLine(_content: DramaContent, _kind: StrainKind, _seed: string): string | null {
  return null; // stub (T1)
}

/** `theme.drama ?? EMPTY_DRAMA`. */
export function dramaFor(theme: Pick<ThemeDefinition, 'drama'>): DramaContent {
  return theme.drama ?? EMPTY_DRAMA;
}

/** "On a roll": records (toolCount, time) samples per agent; a tool-count drop (a new agent reusing an id) resets it. */
export class StreakTracker {
  observe(_agentId: string, _toolCount: number, _nowMs: number): void {} // stub (T1)
  /** True when toolCount rose by >= cfg.streakTools within the last cfg.streakWindowSec. */
  isOnARoll(_agentId: string, _nowMs: number, _cfg: Pick<DramaSettings, 'streakTools' | 'streakWindowSec'>): boolean {
    return false; // stub (T1)
  }
  forget(_agentId: string): void {} // stub (T1)
}
